### ISSUE TITLE
User Story #1: Landing Page with routings

### ISSUE THREAD

**Issue by hamedbahrami479** [hamedbahrami479/CapStone#1]
**_Title:_** Landing Page

Value proposition: As a user I want to open up a lean looking, appealing, sorted and likable first page, with intuitiv graphical displays in order to feel needed, valued and contributing to a meaningful purpose. Ultimately the curiosity of the user should triggered in order to seek more information what GIB is about, which is why the vision and mission sites gain attention.

**Description:** This is the first page seen by the user, from where it should be possible to move into any of the other sections.

The prototype of this site looks as follows: 

<img width="433" alt="Landing Page" src="https://user-images.githubusercontent.com/100590440/165762008-ef7e8093-bf6a-4a4c-b02c-ef066e530218.png">

**Acceptance Criteria:** 

- App name is displayed in upper third of the page 
- Picture as displayed in the prototype is used
- Header is displayed with Vision and Mission icons
- NavBar with three intuitiv icons is displayed with the home icon high lighted in blue, as we are on the first page of the app
- User can click on the buttons and is routed to the corresponding pages (Vision, Mission, Search, Balance)

**Tasks**

- [ ] Design the global styles of this page
- [ ] create the header component 
- [ ] create the NavBar component
- [ ] create the routings to the further pages (Search, Vision, Mission, Balance)

**Comment by PReichetanz** [comment]
Looks good, but the landing page is not your first issue, so you can save it for later in your backlog 🐸
