### ISSUE TITLE
Submit Information Due To no Category match

### ISSUE THREAD

**Issue by hamedbahrami479** [hamedbahrami479/CapStone#11]
_**Title:**_Submit Information via "Not Found?" site

_Value Proposition:_As a user I want to be able to contribute into an expansion when I cannot find my category. E.g.: plastics transparent and plastic black is set, but I have a colorful piece of plastics. 

**_Description:_**
<img width="465" alt="Not Found Page" src="https://user-images.githubusercontent.com/100590440/169809091-60e14654-b15b-4ec6-9a04-7b63b70bd20b.png">

**_Acceptance Criteria:_**

- by choosing "Not Found?" button, the site should appear like it is shown in the prototype
- it is not possible to type any free text in the result box, only via  the chosen product category
- all product categories show the correct results. (e.g. correct result for plastic black) 

**_Tasks:_**

- [x] Work on a separate branch 
- [ ] create a text input component in order to submit information on the category to be set
- [ ] create a setItem function for storing information in the local storage
- [ ] create a button for submitting the information by click
- [ ] create a pop coming up, when the button is used
- [ ] write your test script(s)
