### ISSUE TITLE
User Story #3: Search Function

### ISSUE THREAD

**Issue by hamedbahrami479** [hamedbahrami479/CapStone#3]
_**Title:**_Search Function Page

**_Value Proposition:_** The user has here the possibility to find exact instructions how to proceed with the waste in order to make an educated contribution into sorting still valuable goods and ultimately into a circular world.

**_Description:_**

The process foresees to guide the user through a quick 3 step drop down selection, which are consecutively asked. the product structure 

Prototype of the Search site:

<img width="414" alt="Search Site" src="https://user-images.githubusercontent.com/100590440/165776591-2aea7aa5-76c5-45ca-b5f4-f73d067934a9.png">

Prototype of the Not_Found_Page:

<img width="465" alt="Not Found Page" src="https://user-images.githubusercontent.com/100590440/165777899-abccd584-2763-4573-91ea-9c1323f40ef8.png">

Prototype of the Form Page: 

<img width="465" alt="Bildschirmfoto 2022-04-28 um 16 47 43" src="https://user-images.githubusercontent.com/100590440/165780109-1b01ca80-5891-4d02-94ac-eecb30556ac2.png">

THE PRODUCT STRUCTURE:

<img width="519" alt="Produktstruktur" src="https://user-images.githubusercontent.com/100590440/165783385-01c54941-4b26-4b85-a860-d097d4fa97c2.png">

**_Acceptance Criteria:_**

- The loupe is now high lighted in blue 
- Every other icon is now grey
- Three drop downs appear back to back, not all at once
- In case of data availability, display the information as drafted in the 4th box of the prototype page 
- In case of no data availability display the Not_Found_Page with the Add-Value Button leading to the Form, where the user can now...
- ... choose per drop down what (s)he would like to add to the database (the drop down options should be the same as in the drop downs on the search page)
- Make sure, that the new product just added by the user is now displayed as a result on the search site

**_Tasks:_**

- [ ] design the global styles of the search site
- [ ] design the global styles of the Not-Found site
- [ ] design the global styles of the Form site 
- [ ] define a product structure (three levels)
- [ ] Take and adapt the NavBar component for each site (search, not-found, form)
- [ ] Take and adapt the header component from the Vision/Mission Site for each site (search, not-found, form)
- [ ] Create an input field for the product categories per drop down, no free text!
- [ ] Create the back to back functionality for the drop downs and ultimately the result box.
- [ ] create the routing in order to get to the form when clicking on the Add-Value Button
- [ ] Write the test scripts
