### ISSUE TITLE
User Story: Display Search Result

### ISSUE THREAD

**Issue by hamedbahrami479** [hamedbahrami479/CapStone#6]
_**Title:**_Display Search  Results

_Value Proposition:_As a user I want to receive information and knowledge about the piece of waste I would like to "give back". Therefore it would be good, if the result box would now be able to display the corresponding information in the result box. 

**_Description:_**
<img width="486" alt="Bildschirmfoto 2022-05-06 um 16 06 34" src="https://user-images.githubusercontent.com/100590440/167149483-397e540b-7342-4485-acf1-699dde882a8e.png">

**_Acceptance Criteria:_**

- by choosing a category from the drop down menu, the correct handling information should be displayed in the result box
- it is not possible to type any free text in the result box, only via  the chosen product category
- all product categories show the correct results. (e.g. correct result for plastic black) 

**_Tasks:_**

- [x] Work on a separate branch 
- [x] define useful data properties and store them in a separate data sheet
- [x] create a drop down component with useful categories
- [x] create a filter function in order to fetch correct data from your data sheet, write it in your Result box component
- [x] write your test script(s)

**Comment by hamedbahrami479** [comment]
done
